### ISSUE TITLE
Map out the flows

### ISSUE THREAD

**Issue by GrilloPress** [samanthasaw/nhs-edec#1]
Visualise how the user goes through the system to submit their edec

**Comment by samanthasaw** [comment]
[Return user eDec flow.pdf](https://github.com/samanthasaw/nhs-edec/files/3436353/Return.user.eDec.flow.pdf)

**Comment by samanthasaw** [comment]
[New user eDec flow.pdf](https://github.com/samanthasaw/nhs-edec/files/3436358/New.user.eDec.flow.pdf)
