### ISSUE TITLE
Design how a user can view current and previously submitted declarations

### ISSUE THREAD

**Issue by GrilloPress** [samanthasaw/nhs-edec#13]
Linked to https://github.com/samanthasaw/nhs-edec/issues/12

Design how the user views current and previous submissions.

Before and after final submission date.

**Comment by samanthasaw** [comment]
![reopen submission flow](https://user-images.githubusercontent.com/38656667/62143501-022a6380-b2e8-11e9-9c47-fddfb79aeb63.JPG)

**Comment by samanthasaw** [comment]
I'm thinking a timeline: 

2019
The Nye Practice               Reopen your submission _(link)_ 

2018
The Nye Practice               Download your certificate _(link)_ 

2017

2016

**Comment by samanthasaw** [comment]
Tom is thinking this may be out of scope for the October deadline

**Comment by GrilloPress** [comment]
I think it might be worth confirming if that's true.

But work under the assumption this is nice to have.

So lower priority but not sure how much more there's left to design on this?

**Comment by samanthasaw** [comment]
Design here: http://nhs-edec.herokuapp.com/submit-your-edec/previously-submitted/your-previous-declarations
