### ISSUE TITLE
Design what happens when a section is complete

### ISSUE THREAD

**Issue by samanthasaw** [samanthasaw/nhs-edec#19]
What happens when a user goes into a completed section. 

What happens when a user completes a section

**Comment by GrilloPress** [comment]
Missing disclaimer at start. But rough and ready process flow

![eDec - High level eDec section flow](https://user-images.githubusercontent.com/5756226/61911030-21af3e00-af2e-11e9-890b-86b6422b6dfc.jpg)

**Comment by samanthasaw** [comment]
[Back to your task list]

[Section name]
You’ve confirmed your section name details. 

You can [change your section name details] at any time before submitting your electronic declaration.

**Comment by samanthasaw** [comment]
i think they should see the 'you've confirmed details' page

**Comment by samanthasaw** [comment]
Decide if the button should change

**Comment by samanthasaw** [comment]
Maybe instead of the tag changing, we use a banner that tells them they've updated their answers that they're able to dismiss, for example: 
![image](https://user-images.githubusercontent.com/38656667/63005618-ce694500-be74-11e9-9dfa-517872a86a0c.png)

**Comment by samanthasaw** [comment]
But it could say 'You have updated and confirmed the practice details section. Dismiss

But the tag would still say completed

**Comment by samanthasaw** [comment]
First examples designed for the returns to a completed section page
http://nhs-edec.herokuapp.com/submit-your-edec/sections/premises-equipment/return-user/returns-to-complete-section

http://nhs-edec.herokuapp.com/submit-your-edec/sections/premises-equipment/new-user/returns-to-complete-section
