### ISSUE TITLE
Make the contract end and start date appear in the summary list on practice details journey for APMS contract users

### ISSUE THREAD

**Issue by samanthasaw** [samanthasaw/nhs-edec#31]
Contract start and end dates are not optional for APMS contract users. So if a user has an APMS contract or changes their contract type to APMS, contract start and end date should appear in the summary list, not in a list on their own under 'optional information'.

**Comment by GrilloPress** [comment]
Fixed in http://nhs-edec.herokuapp.com/submit-your-edec/sections/practice-details/return-user/new-practice-details
