### ISSUE TITLE
Design the service error messages

### ISSUE THREAD

**Issue by samanthasaw** [samanthasaw/nhs-edec#50]
This ticket includes: 

- validation messages
- end page messages

But feel free to split it into 2 tickets if that's easier. 

Link to NDOP errors: http://ndop-r.herokuapp.com/opt-out/v1/errors/index

Link to eDec prototype: http://nhs-edec.herokuapp.com/
username: user
password: smartcard

**Acceptance criteria:** 

- We have validation and system error messages
- The messages are in the eDec prototype
- The messages have been shared with the dev team

**Comment by samanthasaw** [comment]
Note - For validation messages, some form questions are optional and some are not. We must make sure that users cannot continue without answering mandatory questions.

**Comment by rhiannonsmith** [comment]
[error messages - edec 03.pptx](https://github.com/samanthasaw/nhs-edec/files/3509996/error.messages.-.edec.03.pptx)

**Comment by rhiannonsmith** [comment]
I've attached the error messages in a powerpoint presentation format. I've added in links to the appropriate questions in the prototype. I've also added some comments in.

**Comment by samanthasaw** [comment]
Links to #96
