### ISSUE TITLE
Get the opening hours to change based on what users enter

### ISSUE THREAD

**Issue by samanthasaw** [samanthasaw/nhs-edec#6]

**Comment by GrilloPress** [comment]
New flow added to prototype http://nhs-edec.herokuapp.com/submit-your-edec/sections/opening-hours

## Concept

User sees card. Data is prepopulated
Sees list of items and can change any day
Each day lets the user update the data
Returns to summary list of items
Which they can submit

![Change opening hours loop_Firefox](https://user-images.githubusercontent.com/5756226/60795191-266ca780-a163-11e9-9abc-f9e33135b3b4.png)

**Comment by GrilloPress** [comment]
Things to do:

decide next steps after they check and confirm their opening times
